return {
    "asparagus_seeds", "carrot_seeds", "corn_seeds", "eggplant_seeds",
    "garlic_seeds", "onion_seeds", "pepper_seeds", "potato_seeds",
    "pumpkin_seeds", "tomato_seeds", "dragonfruit_seeds", "durian_seeds",
    "pomegranate_seeds", "watermelon_seeds", "seeds", "red_cap", "spore_medium",
    "green_cap", "spore_small", "blue_cap", "spore_tall", "lureplantbulb",
    "marblebean", "livingtree_root", "twiggy_nut", "acorn", "pinecone",
    "moonbutterfly", "butterfly", "dug_berrybush", "dug_berrybush2",
    "dug_berrybush_juicy", "dug_grass", "dug_sapling", "dug_sapling_moon",
    "dug_marsh_bush", "dug_rock_avocado_bush", "rock_avocado_fruit_sprout",
    "bullkelp_root", "waterplant_planter","oceantreenut","dug_trap_starfish",
    "dug_bananabush","dug_monkeytail","palmcone_seed","livinglog",
    "treegrowthsolution", "spoiled_food",
    "spoiled_fish","spoiled_fish_small","poop","guano","glommerfuel","compost",
    "compostwrap", "premiumwateringcan", "wateringcan",  "soil_amender", "soil_amender_fermented",
    "farm_plow_item", "plantregistryhat", "nutrientsgoggleshat","farm_hoe",
    "golden_farm_hoe","shovel","goldenshovel","hammer","staff_tornado",
    "asparagus_oversized", "carrot_oversized", "corn_oversized",
    "dragonfruit_oversized", "durian_oversized", "eggplant_oversized",
    "garlic_oversized", "onion_oversized", "pepper_oversized",
    "pomegranate_oversized", "potato_oversized", "pumpkin_oversized",
    "tomato_oversized", "watermelon_oversized", "asparagus_oversized_waxed",
    "carrot_oversized_waxed", "corn_oversized_waxed",
    "dragonfruit_oversized_waxed", "durian_oversized_waxed",
    "eggplant_oversized_waxed", "garlic_oversized_waxed",
    "onion_oversized_waxed", "pepper_oversized_waxed",
    "pomegranate_oversized_waxed", "potato_oversized_waxed",
    "pumpkin_oversized_waxed", "tomato_oversized_waxed",
    "watermelon_oversized_waxed",
}
