return {
    "lightcrab","powder_monkey","prime_mate","polly_rogers","pigman", "pigguard", "bunnyman", "merm", "mermguard", "mermking",
    "little_walrus", "walrus", "knight", "bishop", "rook", "knight_nightmare",
    "bishop_nightmare", "rook_nightmare", "archive_centipede", "spider",
    "spider_warrior", "spider_hider", "spider_spitter", "spider_dropper",
    "spider_moon", "spider_healer", "spider_water",
    "hound", "firehound", "icehound", "mutatedhound",
    "clayhound", "rabbit", "frog", "perd", "catcoon", "mole", "bat", "pondfish",
    "pondeel", "oceanfish_medium_1_inv", "oceanfish_medium_2_inv",
    "oceanfish_medium_3_inv", "oceanfish_medium_4_inv",
    "oceanfish_medium_5_inv", "oceanfish_medium_6_inv",
    "oceanfish_medium_7_inv", "oceanfish_medium_8_inv","oceanfish_medium_9_inv", "oceanfish_small_1_inv",
    "oceanfish_small_2_inv", "oceanfish_small_3_inv", "oceanfish_small_4_inv",
    "oceanfish_small_5_inv", "oceanfish_small_6_inv", "oceanfish_small_7_inv",
    "oceanfish_small_8_inv", "oceanfish_small_9_inv", "wobster_sheller_land",
    "wobster_moonglass_land", "squid", "shark", "gnarwail", "robin",
    "robin_winter", "crow", "puffin", "canary", "canary_poisoned", 
    "bird_mutant","bird_mutant_spitter",
    "buzzard",
    "smallbird", "teenbird", "tallbird", "penguin", "mutated_penguin",
    "babybeefalo", "beefalo", "koalefant_summer", "koalefant_winter",
    "grassgator",

    "lightninggoat", "tentacle_pillar_arm", "tentacle", "tentacle_pillar",
    "bee", "killerbee", "butterfly", "moonbutterfly", "mosquito", "fireflies",
    "dustmoth", "lightflier", "mushgnome", "grassgekko", "carrat_planted",
    "carrat", "carrat_ghostracer", "fruitdragon", "lureplant", "eyeplant",
    "mandrake_active", "spore_tall", "spore_small", "spore_medium", "monkey",
    "slurtle", "snurtle", "rocky", "slurper", "worm", "krampus", "ghost",
    "smallghost", "trap_starfish", "waterplant", "crawlingnightmare",
    "nightmarebeak", "deer", "deer_red", "deer_blue", "lavae", "mossling",
    "beeguard", "gingerbreadpig",
    
    "fruitfly", "stalker_minion", "stalker_minion1",
    "stalker_minion2", "birchnutdrake", "crabking_claw", "moonpig",
    "houndcorpse", "moonhound", "pigelite1", "pigelite2", "pigelite3",
    "pigelite4", "hermitcrab","eyeofterror_mini",
}
