local Wagstaff_tool_strings = {
    requests = {
        wagstaff_tool_1 = {
            en = "Quick, I need my Reticulating Buffer!",
            ch_s = "快，我需要我的网状缓冲器！",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        wagstaff_tool_2 = {
            en = "Someone find me a Widget Deflubber!",
            ch_s = "给我找个装置除垢器去！",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        wagstaff_tool_3 = {
            en = "Has anyone seen my Grommet Scriber?",
            ch_s = "有没有看到我的垫圈开槽器？",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        wagstaff_tool_4 = {
            en = "Can someone hand me the Conceptual Scrubber?",
            ch_s = "能不能给我递一下概念刷洗器？",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        wagstaff_tool_5 = {
            en = "I'm certain I put the Calibrated Perceiver down here somewhere...",
            ch_s = "我分明记得把校准观察机放在附近的……",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
    },
    removestr = {
        WAGSTAFF_NPC_ACCEPT_1 = {
            en = "Excellent, that's it!",
            ch_s = "妙极了，就是它！",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        WAGSTAFF_NPC_ACCEPT_2 = {
            en = "At last! Now let's get this finished!",
            ch_s = "总算找到了！我们来完成它吧！",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },

        WAGSTAFF_NPC_EXPERIMENT_DONE_1 = {
            en = "It's done!",
            ch_s = "完成了！",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        WAGSTAFF_NPC_EXPERIMENT_DONE_2 = {
            en = "Take this, you'll need it for what we have to do.",
            ch_s = "拿着这个，你会需要它去做我们要做的事。",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },

        WAGSTAFF_NPC_EXPERIMENT_FAIL_1 = {
            en = "Balderdash! The containment has failed!",
            ch_s = "废了！我们的实验失败了！",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
        WAGSTAFF_NPC_EXPERIMENT_FAIL_2 = {
            en = "Back to my notes again...",
            ch_s = "重新回到我的笔记……",
            ch_t = nil,
            fr = nil,
            ge = nil,
            it = nil,
            ja = nil,
            ko = nil,
            pol = nil,
            por = nil,
            sp_m = nil,
            sp = nil,
        },
    },
}

return Wagstaff_tool_strings